# get info page
GET http://localhost:3001/info

###

# get all persons
GET http://localhost:3001/api/persons/

###

# get one person of id 2
GET http://localhost:3001/api/persons/63f4a55a600312fa70f2b323

###

# get one person of id that does not exist
GET http://localhost:3001/api/persons/5

###

# delete one person
DELETE http://localhost:3001/api/persons/63f4a6050224f1d1d82a7ce4

###

# add new Person to database
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
  "name": "Artosius Hellaswwwius",
  "number": "123-123-124-55"
}
